AWSTemplateFormatVersion: 2010-09-09
Parameters:
  #
  # In addition to the following parameters,
  # the API Stage needs Systems Manager Secrets:
  # - CloudefficiencyClientId
  # - CloudefficiencyClientSecret
  # - CloudefficiencyJWTSecrets
  # The lambda itself will pull these in python code
  # so they are not otherwise enumerated here.
  #
  APIStackName:
    Type: 'String'
    Description: >
      The name of the stack which includes
      RestApi
  BucketStackName:
    Type: 'String'
    Description: >
      The name of the stack which includes
      StaticBucket of html, css, & javascript
  DeploymentStackName:
    Type: 'String'
    Description: >
      The name of the stack which includes
      Deployment
  BaseURI:
    Type: 'String'
    Description: >
      The base uri to serve the cloudefficiency dashboard.
  AuthorizationEndpoint:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: CloudefficiencyAuthorizationEndpoint
  TokenEndpoint:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: CloudefficiencyTokenEndpoint
  UserinfoEndpoint:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: CloudefficiencyUserinfoEndpoint
Resources:
  APILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${AWS::StackName}-LogGroup"
      RetentionInDays: 7
  APIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt APILogGroup.Arn
      CacheClusterEnabled: false
      DeploymentId:
        Fn::ImportValue:
          !Sub "${DeploymentStackName}-Deployment"
      Description: 'Production Deployment'
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: '*'
          MetricsEnabled: true
          LoggingLevel: "INFO"
          DataTraceEnabled: true
          ThrottlingBurstLimit: 5000
          ThrottlingRateLimit: 10000
          CachingEnabled: false
      RestApiId:
        Fn::ImportValue:
          !Sub "${APIStackName}-RestApi"
      StageName: 'prod'
      Variables:
        authorization_endpoint: !Ref AuthorizationEndpoint
        base_uri: !Ref BaseURI
        bucket_name:
          Fn::ImportValue:
            !Sub "${BucketStackName}-StaticBucket"
        default_object: "redirect_index.html"
        redirect_uri: !Join ['', [!Ref BaseURI, "/callback"]]
        token_endpoint: !Ref TokenEndpoint
        userinfo_endpoint: !Ref UserinfoEndpoint
Outputs:
  Stage:
    Description: API stage
    Value: !Ref APIStage
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-Stage"
