AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ACMCertificateArn:
    Type: 'String'
    Description: >
      The ACM certificate ARN to use in the distribution.
  APIStackName:
    Type: 'String'
    Description: >
      The name of the stack which includes
      APIStage
      LambdaRole
  CNAME:
    Type: 'String'
    Description: >
      The base uri to serve the cloudefficiency dashboard.
  BucketStackName:
    Type: 'String'
    Description: >
      The name of the stack which includes
      CloudfrontLoggingBucket
Resources:
  ProdDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref CNAME
        DefaultCacheBehavior:
          # No Caching for now.
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            Cookies:
              Forward: 'all'
            QueryString: true
          TargetOriginId: !Sub "${AWS::StackName}-prod"
          ViewerProtocolPolicy : 'redirect-to-https'
        Enabled: true
        HttpVersion: 'http2'
        IPV6Enabled: true
        Logging:
          Bucket:
            Fn::Join:
              - ''
              - - Fn::ImportValue:
                    !Sub "${BucketStackName}-CloudfrontLoggingBucket"
                - '.s3.amazonaws.com'
          IncludeCookies: true
        Origins:
          - CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 30
              OriginProtocolPolicy: 'https-only'
              OriginReadTimeout: 60
            DomainName:
              Fn::Sub:
                - '${APIId}.execute-api.${Region}.amazonaws.com'
                - APIId:
                    Fn::ImportValue:
                      !Sub "${APIStackName}-RestApi"
                  Region: !Ref AWS::Region
            Id: !Sub "${AWS::StackName}-prod"
            # This value is hard coded without an import
            # to allow the slow cloudformation distribution
            # to be deployed before code is deployed.
            OriginPath: '/prod'

        PriceClass: 'PriceClass_100'
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateArn
          MinimumProtocolVersion: "TLSv1.1_2016"
          SslSupportMethod: "sni-only"
