AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketStackName:
    Type: 'String'
    Description: >
      The name of the stack which includes
      LambdaCodeBucket
  IAMStackName:
    Type: 'String'
    Description: >
      The name of the stack which includes
      APIGatewayRole
      LambdaRole
  NetworkStackName:
    Type: 'String'
    Description: >
      The name of the stack which includes
        - PrivateSubnet01
        - PrivateSubnet02
        - PrivateSubnet03
        - PrivateSubnet04
        - SecurityGroupDefault
        - SecurityGroupCorpAccess
Resources:
  CloudefficiencyLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
          Fn::ImportValue:
            !Sub "${BucketStackName}-LambdaCodeBucket"
        S3Key: server.zip
      Description: 'cloudefficiency lambda handler'
      FunctionName: 'cloudefficiency-lambda'
      Handler: 'lambda_function.lambda_handler'
      MemorySize: 1024
      Role: !Sub
        - "arn:aws:iam::${Account}:role/${Role}"
        - Account: !Ref AWS::AccountId
          Role:
            Fn::ImportValue:
              !Sub "${IAMStackName}-LambdaRole"
      Runtime: 'python3.6'
      Timeout: 300
      TracingConfig:
        Mode: 'Active'
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-SecurityGroupDefault"
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-SecurityGroupCorpAccess"
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-PrivateSubnet01"
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-PrivateSubnet02"
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-PrivateSubnet03"
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-PrivateSubnet04"

Outputs:
  Lambda:
    Description: >
      cloudefficiency lambda
      - authenticates with keymaster
      - servces s3 static assets
    Value: !Ref CloudefficiencyLambda
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-ServerLambda"
